//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT0720hiep_61133631.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KT0720_61133631Entities : DbContext
    {
        public KT0720_61133631Entities()
            : base("name=KT0720_61133631Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LOP> LOPs { get; set; }
        public virtual DbSet<SINHVIEN> SINHVIENs { get; set; }
    
        public virtual int SinhVien_TimKiem(string mASV, string tENSV)
        {
            var mASVParameter = mASV != null ?
                new ObjectParameter("MASV", mASV) :
                new ObjectParameter("MASV", typeof(string));
    
            var tENSVParameter = tENSV != null ?
                new ObjectParameter("TENSV", tENSV) :
                new ObjectParameter("TENSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhVien_TimKiem", mASVParameter, tENSVParameter);
        }
    }
}
